import fs from "node:fs";
import path from "node:path";

// Post-processing for the static export (adapted from nav-shuttle, generalised to
// 13 locales). Runs after `next build`:
//   1. promote out/en/* -> out/  (English served at the web root, localePrefix
//      "as-needed"); /en is redirected to / via public/_redirects.
//   2. patch <html lang="en"> to the correct BCP-47 tag per locale dir (and add
//      dir="rtl" for Arabic) — the root layout can only emit a single static
//      lang, so we fix it per output dir here.
//   3. regenerate out/sw.js precaching every route + the WASM module.

const out = path.join(process.cwd(), "out");

// non-default locale dir -> { lang, rtl }
const LOCALES = {
  zh: { lang: "zh-CN" },
  "zh-TW": { lang: "zh-Hant" },
  ja: { lang: "ja" },
  ko: { lang: "ko" },
  es: { lang: "es" },
  fr: { lang: "fr" },
  de: { lang: "de" },
  pt: { lang: "pt-BR" },
  ar: { lang: "ar", rtl: true },
  it: { lang: "it" },
  id: { lang: "id" },
  vi: { lang: "vi" },
};

// 1. Promote out/en -> out
const en = path.join(out, "en");
if (fs.existsSync(en)) {
  fs.cpSync(en, out, { recursive: true, force: false, errorOnExist: false });
  fs.rmSync(en, { recursive: true });
  console.log("[postbuild] promoted out/en/* -> out/ and removed out/en");
} else {
  console.log("[postbuild] out/en not found - nothing to promote");
}

// 2. Patch <html lang> (and dir for RTL) per locale dir
function patchLang(dir, lang, rtl) {
  let patched = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      patched += patchLang(p, lang, rtl);
    } else if (entry.name.endsWith(".html")) {
      const html = fs.readFileSync(p, "utf8");
      const next = html.replace(
        '<html lang="en"',
        `<html lang="${lang}"${rtl ? ' dir="rtl"' : ""}`,
      );
      if (next !== html) {
        fs.writeFileSync(p, next);
        patched += 1;
      }
    }
  }
  return patched;
}

for (const [loc, { lang, rtl }] of Object.entries(LOCALES)) {
  const dir = path.join(out, loc);
  if (!fs.existsSync(dir)) continue;
  const n = patchLang(dir, lang, rtl);
  console.log(`[postbuild] patched <html lang> -> ${lang}${rtl ? " dir=rtl" : ""} in ${n} file(s) under out/${loc}`);
}

// 3. Regenerate service worker
function collectRoutes(dir, prefix = "") {
  const routes = [];
  if (fs.existsSync(path.join(dir, "index.html"))) routes.push(prefix + "/");
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith("_") || entry.name === "404") continue;
    routes.push(...collectRoutes(path.join(dir, entry.name), `${prefix}/${entry.name}`));
  }
  return routes;
}

function collectWasm() {
  const wasmDir = path.join(out, "wasm");
  if (!fs.existsSync(wasmDir)) return [];
  return fs
    .readdirSync(wasmDir)
    .filter((f) => f.endsWith(".wasm"))
    .map((f) => `/wasm/${f}`);
}

const routes = collectRoutes(out);
const extras = ["/manifest.webmanifest", "/icon-192.png", "/icon-512.png"].filter(
  (p) => fs.existsSync(path.join(out, p.replace(/\/$/, ""))),
);
const precache = [...new Set([...routes, ...extras, ...collectWasm()])];
const version = `v${Date.now()}`;

const sw = `// Generated by scripts/postbuild.mjs — do not edit by hand.
const CACHE = "image-shuttle-${version}";
const PRECACHE = ${JSON.stringify(precache, null, 0)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      await Promise.allSettled(
        PRECACHE.map((url) =>
          fetch(url, { cache: "reload" })
            .then((res) => (res.ok ? cache.put(url, res) : null))
            .catch(() => {})
        )
      );
    })
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;

  if (url.pathname.startsWith("/_next/static/") || url.pathname.startsWith("/wasm/")) {
    event.respondWith(
      caches.open(CACHE).then((cache) =>
        cache.match(request).then(
          (hit) =>
            hit ||
            fetch(request).then((res) => {
              if (res.ok) cache.put(request, res.clone());
              return res;
            })
        )
      )
    );
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const clone = res.clone();
          caches.open(CACHE).then((cache) => cache.put(request, clone));
          return res;
        })
        .catch(() => caches.match(request).then((hit) => hit || caches.match("/")))
    );
    return;
  }

  event.respondWith(
    caches.open(CACHE).then((cache) =>
      cache.match(request).then((hit) => {
        const fetching = fetch(request)
          .then((res) => {
            if (res.ok) cache.put(request, res.clone());
            return res;
          })
          .catch(() => hit);
        return hit || fetching;
      })
    )
  );
});
`;
fs.writeFileSync(path.join(out, "sw.js"), sw);
console.log(`[postbuild] generated out/sw.js — ${precache.length} precached URLs, cache ${version}`);
